sudo: false

install:
  # stack
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack --version
  # elm
  - npm install -g elm@0.19.1-3 elm-test@0.19.1-revision2

script:
  - make setup
  - make test
  - make build

cache:
  directories:
    - $HOME/.stack
