resolver: lts-8.0

packages:
  - location: ./.
  - location:
      git: https://www.github.com/soenkehahn/wai-make-assets
      commit: c72a924
    extra-dep: true
  - location:
      git: https://github.com/krisajenkins/elm-export
      commit: 94b939b
    extra-dep: true
  - location:
      git: https://www.github.com/mattjbray/servant-elm
      commit: 301179e
    extra-dep: true
